### ISSUE TITLE
Error while using regex on Responce

### ISSUE THREAD

**Issue by BSec** [nccgroup/BurpSuiteLoggerPlusPlus#18]
Hi Soroush Dalili,

Today i got below errors when used regex to filter comments from all responses.
(/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*+/)|(//.*) - to filter the comments from response,

at java.util.regex.Pattern$Branch.match(Unknown Source)
at java.util.regex.Pattern$GroupHead.match(Unknown Source)
at java.util.regex.Pattern$Loop.match(Unknown Source)
at java.util.regex.Pattern$GroupTail.match(Unknown Source)
at java.util.regex.Pattern$BranchConn.match(Unknown Source)
at java.util.regex.Pattern$CharProperty.match(Unknown Source)

request you to look into it. Thanks in advance.

Regards
Bhaskar from BaanuTech

**Comment by irsdl** [comment]
It seems you regular expression is not in correct format. You can check it online as well for example via https://regex101.com/ or http://www.regexr.com/
I will add an option to the application to warn you when the provided regex was invalid.

**Comment by BSec** [comment]
thank you !!
