### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid UUID string

### ISSUE THREAD

**Issue by Hipapheralkus** [nccgroup/BurpSuiteLoggerPlusPlus#59]
I'm using Logger++ 3.1. I have 2 Burp instances running, both of which have Logger++ running (not sure if it matters). In the Extensions -> Errors I can see following trace:
```
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 70ffd63b-b6db-4e34-a7fc-785a60bba3fc$;$LPP:4dbd49ff-5672-4232-b070-93242711cd3f
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 7c88adcf-2365-4dba-ab01-ab920d6d9d1a$;$LPP:51c810df-83aa-43ca-a6e9-01c6cc2b4f46
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: b1034e5c-ddd2-4c0b-9639-a95f84a2833e$;$LPP:bb774595-da3e-49be-aba8-6c1b66a80d5a
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: db12cdbe-0a65-4d01-89f6-17573222d360$;$LPP:de496ef7-b467-460b-af1d-da56082456ac
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: ba0a9cfc-f2ce-4b95-959f-09d325f281f8$;$LPP:b6290178-9999-497c-bd16-4e2ed5fd6cbd
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 60f3481a-1942-474a-850d-c6469ab58d53$;$LPP:d1839a37-b1b1-4b1d-a642-975c640a9c4e
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 578b7870-a994-4383-9119-5272b4d71c76$;$LPP:4a173255-d3fc-42db-a7e6-097c51379374
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 8bb89fcb-17f5-46b4-98e9-0dc0ef1eee7f$;$LPP:5d5a60cc-c584-4757-9831-3f48870af539
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 33ae7389-019d-484e-8b54-86572327cff2$;$LPP:41b7f4c9-6a8d-489e-ba2b-4945a040f8e7
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 77027cff-ab31-4ce8-bd77-27cdb0adf937$;$LPP:c77b7ce9-4a47-46b2-b192-5ad48cc9d1e2
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 0e18bb38-a0c3-4418-a4ea-9549444d889a$;$LPP:241f5827-b1ab-4049-af02-1183803ccb34
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: bcf7bfbe-cba1-4ad5-b73a-e9e518ab73f0$;$LPP:f40f3f7d-9b82-4685-b32b-c392be5ca0ba
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 4e580982-63a9-46e3-9a36-67cc4a763f4e$;$LPP:1edcb821-fe79-4bdf-9849-c555af06350f
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 67f08067-9567-4046-87d5-e41f4a8d8b5c$;$LPP:cef1e10e-057c-4cbd-a89d-c4e73a8d4d60
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 96f88b41-fa82-4e2e-8997-3b10620bfc3c$;$LPP:af9caf74-0427-4d5a-a855-25ae675413dc
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 031f946a-4e7c-4d09-be70-079f084e320d$;$LPP:314d1027-0b1c-48a8-92a2-0a19123a55f8
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 499f296e-60d6-4329-8694-865c4a2791ca$;$LPP:090c449d-c6b4-485e-bd9d-1edc0ff67e05
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: e4c4e2c4-5487-4b8b-aa4c-c9dfff07e67d$;$LPP:2296c265-0af4-4364-a75f-08d4168cf802
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 801f6637-c5d8-42e4-9afd-8f64102b7b8a$;$LPP:a5361f64-09c1-403e-beb7-dd7c63e23210
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 46e8c835-d861-41aa-982a-160d3578648f$;$LPP:47515abb-6b7e-436d-b4a3-1ba60d3e2a5e
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: fcbb8eb1-9d2d-4bdb-9c77-4d1895262d4e$;$LPP:0b6b44d6-82f9-4fe5-9cea-65ca8a011294
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: d233862b-c075-428d-a091-25fb129ace84$;$LPP:180ccfa7-45b5-4405-920e-2fd6fe4a542b
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: c22742b5-8771-437d-b62f-87a22ab0c949$;$LPP:52520f9b-3d64-4d07-8ec8-8d7ec1b94be7
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: de4ea260-4c90-42ac-9492-6c59409cbfd0$;$LPP:58a39f91-3af4-4bc5-94e1-9aefa6d7a713
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 850ff1c8-1c8a-4015-a888-14d25785242c$;$LPP:9c81f21a-a6ad-48f4-a3bf-b840eaf6c0e7
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: a7fd890a-8ef5-4f17-a6fa-cf8cfcd3bd9c$;$LPP:35a62adf-017c-4dd1-95c0-4e7f748b92b3
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: 3058d83c-ca53-4a3f-a28d-f010efe58751$;$LPP:37f2b54e-133f-46ef-b812-b7dbd194de71
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: b154844e-8455-4765-9437-6855ef6b2e61$;$LPP:61de9a69-0489-478d-9301-c62dcd6e4c77
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Invalid UUID string: bc777568-4498-4106-937e-1f5ffd5e1c5e$;$LPP:5abf4059-0cc2-4e3c-b061-854559528eba
	at java.util.UUID.fromString(UUID.java:194)
	at loggerplusplus.LogManager.processHttpMessage(LogManager.java:99)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by CoreyD97** [comment]
Ah, looks like both are adding their UUID tracker to the requests but the regex is greedy and grabs both as one value. A temporary workaround may be to disable Live proxying for other tools in the logger++ options for one of the burp instances.

**Comment by CoreyD97** [comment]
This should be fixed in the latest release currently in the development branch. 
It will be merged into master soon.

Thanks.
