### ISSUE TITLE
My fault

### ISSUE THREAD

**Issue by jinyu00** [nccgroup/BurpSuiteLoggerPlusPlus#61]
The log

```
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.a3_.a(Unknown Source)
	at burp.a3_.<init>(Unknown Source)
	at burp.gcg.a(Unknown Source)
	at burp.ao3.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by CoreyD97** [comment]
Hello,

From the title change I assume this is not an issue with the plugin but a mistake on your end?
If so I'll close the issue :)

Thanks,
Corey
