### ISSUE TITLE
Logger++ Exception Upon Install in Burp Suite 2.0.14beta

### ISSUE THREAD

**Issue by sekhmetn** [nccgroup/BurpSuiteLoggerPlusPlus#65]
In the latest version of BurpSuite 2.x (2.0.14beta), the logger++ extension fails to load when installed from the bapp store (Screenshot below).
![loggerplusplusburp2 0 14betaerror](https://user-images.githubusercontent.com/1099765/51635298-15fda300-1f1c-11e9-9e01-13f501956667.png)

Here's the full error message:
java.lang.RuntimeException: Unable to invoke no-args constructor for class java.awt.Color. Registering an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at loggerplusplus.LoggerPreferences.loadAllSettings(LoggerPreferences.java:415)
	at loggerplusplus.LoggerPreferences.<init>(LoggerPreferences.java:392)
	at loggerplusplus.LoggerPlusPlus.registerExtenderCallbacks(LoggerPlusPlus.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at burp.esk.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class java.awt.Color
	at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:104)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
	... 22 more

**Comment by CoreyD97** [comment]
Hey, thanks for this! I've not tried this on v2.14 beta but can confirm it works on v2. 13 beta. If you don't require the latest burp update for a particular reason you could use this if you needed the plugin.

I will take a look at the cause of the issue tomorrow though looking at that stack trace can't think of a reason why this would be happening though can at least have the plugin soft fail at this error and simply not load the color filters until a fix is found.

**Comment by Mijobar** [comment]
Any update on this issue? 

Thanks!

**Comment by CoreyD97** [comment]
Hello,

Apologies, I've not been able to replicate this issue but am in the process of overhauling the storage of settings and other major areas of the extension. 

One fix to try may be to delete the extensions configuration files from within burps application directory (I believe this is in AppData for Windows and .local for Linux) though be aware this will delete all your preferences for the extension.

Thanks, 
Corey

**Comment by ccsplit** [comment]
@CoreyD97, removing the extension completely (including config files) and reinstalling does not appear to resolve the issue. However, I have been able to use [fx-gson's ColorTypeAdapter](https://github.com/joffrey-bion/fx-gson/blob/master/src/main/java/org/hildan/fxgson/adapters/extras/ColorTypeAdapter.java) for reference and add a GSON TypeAdapter which appears to work. I haven't found out what directly caused this issue when changing from 2.0.13b => 2.0.14b. The current issue however, is it does not properly Colorize the output, but this was a minor issue for me as I don't use that functionality.

**Comment by ncoblentz** [comment]
I just upgraded Burp to 2.0.15 and the issue is fixed. I think it was a problem with Burp suite... Their release notes hints at this saying "This includes a bug that prevented some BApps from working with the bundled version of Java 11." (http://releases.portswigger.net/2019/01/professional-2015beta.html)

**Comment by ncoblentz** [comment]
You're welcome. Thanks for being so responsive initially.
